# -*- coding: utf-8 -*-
"""5.1.scripts-dio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iOlJ8bvqGWuXpLlAoIQibr6YI-xp236o

# 📂 Trabalhando com arquivos e dados externos em python

**Professora:** Dra. Isadora Garcia Ferrão

📧 [instagram](https://www.instagram.com/isadora.ferrao/)

🌐 [linkedin](https://www.linkedin.com/in/isadora-ferrao/)

---

# Introdução ao arquivos e dados externos

## O que são dados externos?

Em muitos programas, os dados **não ficam dentro do código**.

Eles ficam em **arquivos externos**, como por exemplo:

- arquivos de texto
- planilhas
- bancos de dados
- APIs na internet

Python consegue:

- ler esses dados
- processar informações
- salvar novos resultados

Isso é essencial para trabalhar com **dados reais**.

---

## Tipos de arquivos mais comuns

Alguns formatos são muito usados em programação:

| Tipo | Uso |
|-----|-----|
| TXT | Texto simples |
| CSV | Tabelas e planilhas |
| JSON | Estrutura de dados usada em APIs |
| Banco de dados | Armazenamento estruturado |

Nesta aula vamos trabalhar com **TXT, CSV e JSON**.

---

## Função `open()`

Para trabalhar com arquivos em Python usamos a função `open()`.

Estrutura básica:

open("dados.txt", "r")

Os modos mais comuns são:

| Modo | Significado |
|-----|-----|
| r | leitura |
| w | escrita (apaga o conteúdo antigo) |
| a | adicionar conteúdo |

---

## Leitura de arquivos

Para ler um arquivo usamos o modo **"r" (read)**.

Isso permite acessar o conteúdo do arquivo sem modificá-lo.
"""

# Criando um arquivo para teste

with open("dados.txt", "w") as arquivo:
    arquivo.write("Python é uma linguagem poderosa.\n")
    arquivo.write("Estamos aprendendo arquivos.")

# Lendo o arquivo completo

# %%
with open("dados.txt", "r") as arquivo:
    conteudo = arquivo.read()

print(conteudo)

"""## Função `read()`


- `read()` lê todo o conteúdo do arquivo
- o conteúdo é retornado como texto
- podemos armazenar em uma variável
"""

# Lendo linha por linha

with open("dados.txt", "r") as arquivo:
    for linha in arquivo:
        print(linha.strip())

"""## Função `write()`

Para gravar informações em um arquivo usamos o modo **"w" (write)**.

Esse modo cria o arquivo caso ele não exista.

Se o arquivo já existir, o conteúdo anterior será apagado.
"""

# Escrevendo em um arquivo

with open("relatorio.txt", "w") as arquivo:
    arquivo.write("Relatório de vendas\n")
    arquivo.write("Total: 1500")

# Adicionando conteúdo ao arquivo

with open("relatorio.txt", "a") as arquivo:
    arquivo.write("\nNovo registro adicionado.")

# Lendo linha por linha

with open("relatorio.txt", "r") as arquivo:
    for linha in arquivo:
        print(linha.strip())

"""## Módulo CSV

Arquivos CSV são usados para representar **tabelas de dados**.

Eles são muito comuns em:

- planilhas
- análise de dados
- exportação de sistemas

Python possui um módulo chamado **csv** para facilitar o trabalho com esse formato.
"""

import csv

# criando um arquivo CSV

dados = [
    ["nome", "idade", "cidade"],
    ["Ana", 25, "São Paulo"],
    ["Carlos", 30, "Rio de Janeiro"],
    ["Maria", 28, "Belo Horizonte"]
]

with open("pessoas.csv", "w", newline="") as arquivo:
    writer = csv.writer(arquivo)
    writer.writerows(dados)

# lendo um CSV

import csv

with open("pessoas.csv", "r") as arquivo:
    leitor = csv.reader(arquivo)

    for linha in leitor:
        print(linha)

"""## Módulo JSON

JSON é um formato usado para armazenar e transmitir dados estruturados.

Ele é muito usado em:

- APIs
- aplicações web
- armazenamento de dados

Python possui o módulo **json** para trabalhar com esse formato.
"""

import json

dados = {
    "nome": "Ana",
    "idade": 25,
    "cidade": "São Paulo"
}

with open("usuario.json", "w") as arquivo:
    json.dump(dados, arquivo)

# lendo JSON

import json

with open("usuario.json", "r") as arquivo:
    dados = json.load(arquivo)

print(dados)

"""# Integração com bancos de dados e APIs

## O que é uma API?

API significa **Application Programming Interface**.

Uma API permite que **um sistema forneça dados para outro sistema**.

Ou seja, em vez de acessar diretamente um banco de dados ou arquivo, podemos **pedir informações para um serviço na internet**.

Exemplos de APIs populares:

- previsão do tempo
- dados de criptomoedas
- dados de usuários
- mapas e localização

Normalmente as APIs retornam dados no formato **JSON**.

## Requisições HTTP

Para acessar uma API precisamos fazer uma **requisição HTTP**.

O tipo mais comum é:

GET → usado para **buscar dados**

Em Python usamos a biblioteca **requests** para fazer requisições.
"""

# import requests

#url = "https://api.agify.io/?name=ana"

#resposta = requests.get(url)

#print(resposta.status_code)
#print(resposta.text)

"""# Leitura de dados externos (API)

A maioria das APIs retorna dados no formato **JSON**.

Podemos converter essa resposta diretamente para um **dicionário Python**.


"""

# import requests

# url = "https://api.agify.io/?name=ana"

# resposta = requests.get(url)

# dados = resposta.json()

# print(dados)

print("Nome:", dados["name"])
print("Idade estimada:", dados["age"])
print("Número de registros:", dados["count"])

"""## Salvando dados da API

Depois de coletar dados de uma API, podemos salvar esses dados em um arquivo.

Isso permite criar **relatórios ou bases de dados locais**.
"""

# import json
# import requests

# url = "https://api.agify.io/?name=ana"

# resposta = requests.get(url)

# dados = resposta.json()

with open("dados_api.json", "w") as arquivo:
    json.dump(dados, arquivo)

"""## Integração com banco de dados

Além de arquivos, também podemos armazenar dados em **bancos de dados**.

Um banco de dados permite:

- armazenar grandes quantidades de informação
- organizar dados em tabelas
- consultar dados rapidamente

Em Python podemos usar vários bancos de dados.

Para aprender o conceito, vamos usar **SQLite**, que já vem com Python.
"""

import sqlite3

# criando ou conectando ao banco

conexao = sqlite3.connect("dados.db")

cursor = conexao.cursor()

cursor.execute("""
CREATE TABLE usuarios (
    nome TEXT,
    idade INTEGER
)
""")

conexao.commit()

# Inserindo dados no banco

import sqlite3

conexao = sqlite3.connect("dados.db")

cursor = conexao.cursor()

cursor.execute(
    "INSERT INTO usuarios VALUES (?, ?)",
    ("Ana", 25)
)

conexao.commit()

# Lendo os dados

import sqlite3

conexao = sqlite3.connect("dados.db")

cursor = conexao.cursor()

cursor.execute("SELECT * FROM usuarios")

dados = cursor.fetchall()

print(dados)

"""# Boas práticas de segurança e integridade

Quando trabalhamos com dados externos, podem ocorrer vários problemas:

- arquivos inexistentes
- dados inválidos
- arquivos corrompidos
- erros de leitura

Por isso, é importante aplicar boas práticas para garantir que o programa seja **seguro e confiável**.

## Exemplo com boas práticas

Agora vamos juntar algumas das práticas:

- verificar se o arquivo existe
- tratar erros
- validar dados
"""

import os

arquivo = "dados.txt"

if os.path.exists(arquivo):

    try:
        with open(arquivo, "r") as f:
            for linha in f:
                valor = linha.strip()

                if valor.isdigit():
                    print("Número válido:", valor)
                else:
                    print("Valor inválido:", valor)

    except Exception as erro:
        print("Erro ao ler arquivo:", erro)

else:
    print("Arquivo não encontrado.")

"""# Automatizando importação e exportação de dados

Em muitos sistemas, os dados precisam ser processados automaticamente.

Por exemplo:

- ler um arquivo de vendas todos os dias
- processar os dados
- gerar um relatório
- salvar os resultados

Esse processo automático é chamado de **automação de dados**.

Muitas empresas utilizam esse tipo de automação para:

- análise de dados
- relatórios automáticos
- integração entre sistemas
"""

import csv
import json

total = 0

# etapa 1: importar dados
with open("pessoas.csv", "r") as arquivo:
    leitor = csv.reader(arquivo)

    next(leitor)

    # etapa 2: processar dados
    for linha in leitor:
        valor = float(linha[1])
        total += valor

# etapa 3: gerar resultado
resultado = {
    "total_vendas": total
}

# etapa 4: salvar relatório
with open("relatorio.json", "w") as arquivo:
    json.dump(resultado, arquivo)

print("Pipeline executado com sucesso.")